spring:
  cloud:
    azure:    
      #profile: # spring.cloud.azure.profile
        # subscription-id:
        # tenant-id: ${SPRING_CLOUD_AZURE_TENANT_ID}
      #credential:
        #managed-identity-enabled: true        
      keyvault:
        secret:
          enabled: true
          property-source-enabled: true
          # endpoint: ${SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT}
          property-sources:
            - name: kv-cfg-test
              endpoint: ${SPRING_CLOUD_AZURE_KEY_VAULT_ENDPOINT}
              credential:
                managed-identity-enabled: true
                client-id: ${TEST_SVC_APP_IDENTITY_CLIENT_ID} 

# Logging
logging.level.root: WARN
logging.level.org.springframework: INFO

---

spring:
    config:
        activate:
            on-profile: mi
titi: test MI

---

spring:
  config:
    activate:
      on-profile: mi
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    initialization-mode: NEVER # ALWAYS